#!/usr/bin/env bash

set -ex

for CASK in $(grep . Caskfile | grep -v "#"); do
  brew cask install --appdir=/Applications $CASK
done

if [ "$OSX_VERSION" == "10.9" ]; then
  brew cask install --appdir=/Applications caffeine rightzoom
fi

if [ "$OSX_VERSION" == "10.10" ]; then
  brew cask install --appdir=/Applications keepingyouawake
fi

brew cleanup
brew cask cleanup
