#!/usr/bin/env bash

set -ex

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  echo '##### Installing oh-my-zsh'
  curl -L http://install.ohmyz.sh | sh

  git checkout -- .zshrc
else
  echo '##### Updating oh-my-zsh'
  env ZSH=$ZSH /bin/sh $ZSH/tools/upgrade.sh
fi
