#!/usr/bin/env bash

set -ex

if [ ! -f "/usr/local/bin/brew" ]; then
    echo '##### Installing Homebrew'
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    echo '##### Updating & checking homebrew installation'
    brew update
    brew doctor
fi
