#!/usr/bin/env bash

set -ex

export OSX_VERSION=$(sw_vers -productVersion | awk -F '.' '{print $1 "." $2}')

run_app() {
  for APP; do
    if test "$(osascript -e "tell application \"System Events\" to (name of processes) contains \"$APP\"")" = "false"; then
      open -a "$APP"
    fi
  done
}

./steps/install-brew
./steps/install-ohmyzsh
./steps/install-taps
./steps/install-tools
./steps/install-apps
./steps/update-settings
./steps/setup-fde

for APP in "Activity Monitor" "cfprefsd" "Dock" "Finder" "Google Chrome" "SystemUIServer"; do
  killall "$APP" &> /dev/null || true
done

for APP in "Flux" "Dropbox" "Alfred 2" "InsertPic"; do
  run_app "$APP" || true
done

if [ "$OSX_VERSION" == "10.9" ]; then {
  run_app "Caffeine" "RightZoom" || true
}

if [ "$OSX_VERSION" == "10.10" ]; then {
 run_app "KeepingYouAwake" || true
}
