## Productive stuff
ack
httpie
wget
autojump

## Programming stuff
git
bzr
hub
cloc
go
graphviz
jq
ssh-copy-id
tree
awscli

## Shell stuff
zsh
zsh-completions
zsh-syntax-highlighting

## Misc
dockutil
